### ISSUE TITLE
Missing test file

### ISSUE THREAD

**Issue by lirantal** [fagbokforlaget/pdftotextjs#8]
Tests are looking for a file called `invalidfile.pdf` which is missing:
```js
    it('should add options', function(){
      var ptext = new pdftotext(__dirname + '/pdfs/invalidfile.pdf');
```

**Comment by iapain** [comment]
@lirantal Thats fine and error handler should be invoked when error occurs. May be you can describe this test better.

**Comment by lirantal** [comment]
that `invalidfile.pdf` doesn't exist at all so obviously anything that test tries to do will fail. So either that file is accidentally missing, or if we deliberately want to fail the test on missing file then I think the test should be corrected as well as it's name which doesn't suggest it.

**Comment by iapain** [comment]
It's deliberately missing but totally agree with you that we should describe it better.

**Comment by lirantal** [comment]
Okie, I'll fix the test.

**Comment by lirantal** [comment]
Closing via https://github.com/fagbokforlaget/pdftotextjs/pull/10
